version: '3'
services:
  appserver:
    build:
      context: flask_app
      dockerfile: Dockerfile
    container_name: ptax_appserver
    image: ptax_appserver
    restart: unless-stopped
    environment:
      APP_DEBUG: 'False'
      APP_PORT: 8080
    volumes:
      - ptax_appserver_data:/var/www
    networks:
      - backend
      - frontend

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: ptax_webserver
    container_name: ptax_webserver
    restart: unless-stopped
    environment:
      APP_NAME: 'webserver'
      APP_DEBUG: 'true'
      SERVICE_NAME: 'webserver'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - appserver
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  ptax_appserver_data:
    driver: local
  nginxdata:
    driver: local
