version: '3'
services:
  flask:
    build:
      context: flask_app
      dockerfile: Dockerfile
    container_name: ptax_flask
    image: ptax_flask
    restart: unless-stopped
    environment:
      FLASK_DEBUG: 'False'
      FLASK_PORT: 8080
    volumes:
      - ptax_flask_data:/var/www
    network_mode: host

volumes:
  ptax_flask_data:
    driver: local
